# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift
xcode_workspace: Example/PrefsMate.xcworkspace
xcode_scheme: PrefsMate-Example
podfile: Example/Podfile
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/PrefsMate.xcworkspace -scheme PrefsMate-Example -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- xcodebuild -version
