# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode9
env:
  global:
    - WORKSPACE=Example/PrefsMate.xcworkspace
    - SCHEME=PrefsMate-Example
    - SDK=iphonesimulator11.0
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6s"
podfile: Example/Podfile
script:
- set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
